[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.4.0"
derive_more = { version = "2.1.1", features = ["display"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
